/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Nabila Basharahil
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtxtnama = new javax.swing.JTextField();
        jtxtalamat = new javax.swing.JTextField();
        jtxtusia = new javax.swing.JTextField();
        jtxtjenis = new javax.swing.JTextField();
        jtxtgol = new javax.swing.JTextField();
        jtxtstatus = new javax.swing.JTextField();
        jtxtkewar = new javax.swing.JTextField();
        jtxtspesial = new javax.swing.JTextField();
        jtxtwaktu = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jconadokt = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 255, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Identitas"));
        jPanel1.setLayout(null);

        jLabel2.setText("Nama");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(16, 30, 90, 14);

        jLabel3.setText("Alamat");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(16, 61, 90, 14);

        jLabel4.setText("Usia");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(16, 89, 70, 14);

        jLabel5.setText("Jenis Kelamin");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(16, 115, 90, 14);

        jLabel6.setText("Gol. Darah");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(16, 141, 80, 14);

        jLabel7.setText("Status");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(16, 167, 80, 14);

        jLabel8.setText("Kewarganegaraan");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(16, 193, 88, 14);

        jLabel9.setText("Waktu Praktek");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(16, 219, 90, 14);

        jLabel10.setText("Dokter Spesialis");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(16, 245, 100, 14);

        jtxtnama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtnamaActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtnama);
        jtxtnama.setBounds(126, 27, 128, 20);

        jtxtalamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtalamatActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtalamat);
        jtxtalamat.setBounds(126, 58, 128, 20);
        jPanel1.add(jtxtusia);
        jtxtusia.setBounds(126, 89, 128, 20);
        jPanel1.add(jtxtjenis);
        jtxtjenis.setBounds(126, 115, 128, 20);
        jPanel1.add(jtxtgol);
        jtxtgol.setBounds(126, 141, 128, 20);

        jtxtstatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtstatusActionPerformed(evt);
            }
        });
        jPanel1.add(jtxtstatus);
        jtxtstatus.setBounds(126, 167, 128, 20);
        jPanel1.add(jtxtkewar);
        jtxtkewar.setBounds(126, 193, 128, 20);
        jPanel1.add(jtxtspesial);
        jtxtspesial.setBounds(126, 219, 128, 20);
        jPanel1.add(jtxtwaktu);
        jtxtwaktu.setBounds(126, 245, 128, 20);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(50, 130, 270, 310);
        jPanel1.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setFont(new java.awt.Font("Tw Cen MT Condensed", 0, 36)); // NOI18N
        jLabel1.setText("Pemilihan Dokter");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 30, 210, 40);

        jLabel11.setText("Pilih Dokter");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(50, 90, 70, 14);

        jconadokt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih salah satu", "DR. Farras Yassar", "DR. Anisa Putri", "DR. Harun Fajar" }));
        jconadokt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jconadoktActionPerformed(evt);
            }
        });
        getContentPane().add(jconadokt);
        jconadokt.setBounds(180, 90, 140, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxtnamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtnamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtnamaActionPerformed

    private void jconadoktActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jconadoktActionPerformed
        // TODO add your handling code here:
         if(jconadokt.getSelectedItem().equals("DR. Farras Yassar")){             
            jtxtnama.setText("DR. Farras Yassar ");             
            jtxtalamat.setText("Jl. Surabaya 16, Malang");             
            jtxtusia.setText("20 Tahun");             
            jtxtjenis.setText("Laki-Laki");             
            jtxtgol.setText("A");             
            jtxtstatus.setText("Belum Menikah ");             
            jtxtkewar.setText("Indonesia");             
            jtxtspesial.setText("Dokter Umum");             
            jtxtwaktu.setText(" Pagi (07.00-15.00)");         
         }else
             if(jconadokt.getSelectedItem().equals("DR. Anisa Putri")){             
             jtxtnama.setText("DR. Anisa Putri");
             jtxtalamat.setText("Jl. Veteran 3, Malang");             
             jtxtusia.setText("20 Tahun");             
             jtxtjenis.setText("Perempuan");             
             jtxtgol.setText("O");             
             jtxtstatus.setText("Belum Menikah"); 
              jtxtkewar.setText("Indonesia");             
              jtxtspesial.setText("Dokter Gigi");             
              jtxtwaktu.setText(" Sore (16.00-22.00)");         
             }else 
            if((jconadokt.getSelectedItem().equals("DR. Harun Fajar"))){
                 jtxtnama.setText("DR. Harun Fajar ");             
                 jtxtalamat.setText("Jl. Bandung 9, Malang");             
                 jtxtusia.setText("20 Tahun");             
                 jtxtjenis.setText("Laki-Laki");             
                 jtxtgol.setText("B");             
                 jtxtstatus.setText("Belum Menikah");             
                 jtxtkewar.setText("Indonesia");             
                 jtxtspesial.setText("Dokter Gizi");             
                 jtxtwaktu.setText(" Malam (22.00-06.00)"); 
                
            } 
                
            
    }//GEN-LAST:event_jconadoktActionPerformed

    private void jtxtstatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtstatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtstatusActionPerformed

    private void jtxtalamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtalamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtalamatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> jconadokt;
    private javax.swing.JTextField jtxtalamat;
    private javax.swing.JTextField jtxtgol;
    private javax.swing.JTextField jtxtjenis;
    private javax.swing.JTextField jtxtkewar;
    private javax.swing.JTextField jtxtnama;
    private javax.swing.JTextField jtxtspesial;
    private javax.swing.JTextField jtxtstatus;
    private javax.swing.JTextField jtxtusia;
    private javax.swing.JTextField jtxtwaktu;
    // End of variables declaration//GEN-END:variables
}
